// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package boardv1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Board         protoreflect.MessageDescriptor
	fd_Board_id      protoreflect.FieldDescriptor
	fd_Board_name    protoreflect.FieldDescriptor
	fd_Board_size_x  protoreflect.FieldDescriptor
	fd_Board_size_y  protoreflect.FieldDescriptor
	fd_Board_creator protoreflect.FieldDescriptor
	fd_Board_admin   protoreflect.FieldDescriptor
)

func init() {
	file_iplace_board_v1_board_proto_init()
	md_Board = File_iplace_board_v1_board_proto.Messages().ByName("Board")
	fd_Board_id = md_Board.Fields().ByName("id")
	fd_Board_name = md_Board.Fields().ByName("name")
	fd_Board_size_x = md_Board.Fields().ByName("size_x")
	fd_Board_size_y = md_Board.Fields().ByName("size_y")
	fd_Board_creator = md_Board.Fields().ByName("creator")
	fd_Board_admin = md_Board.Fields().ByName("admin")
}

var _ protoreflect.Message = (*fastReflection_Board)(nil)

type fastReflection_Board Board

func (x *Board) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Board)(x)
}

func (x *Board) slowProtoReflect() protoreflect.Message {
	mi := &file_iplace_board_v1_board_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Board_messageType fastReflection_Board_messageType
var _ protoreflect.MessageType = fastReflection_Board_messageType{}

type fastReflection_Board_messageType struct{}

func (x fastReflection_Board_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Board)(nil)
}
func (x fastReflection_Board_messageType) New() protoreflect.Message {
	return new(fastReflection_Board)
}
func (x fastReflection_Board_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Board
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Board) Descriptor() protoreflect.MessageDescriptor {
	return md_Board
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Board) Type() protoreflect.MessageType {
	return _fastReflection_Board_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Board) New() protoreflect.Message {
	return new(fastReflection_Board)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Board) Interface() protoreflect.ProtoMessage {
	return (*Board)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Board) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint32(0) {
		value := protoreflect.ValueOfUint32(x.Id)
		if !f(fd_Board_id, value) {
			return
		}
	}
	if x.Name != "" {
		value := protoreflect.ValueOfString(x.Name)
		if !f(fd_Board_name, value) {
			return
		}
	}
	if x.SizeX != uint32(0) {
		value := protoreflect.ValueOfUint32(x.SizeX)
		if !f(fd_Board_size_x, value) {
			return
		}
	}
	if x.SizeY != uint32(0) {
		value := protoreflect.ValueOfUint32(x.SizeY)
		if !f(fd_Board_size_y, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_Board_creator, value) {
			return
		}
	}
	if x.Admin != "" {
		value := protoreflect.ValueOfString(x.Admin)
		if !f(fd_Board_admin, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Board) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "iplace.board.v1.Board.id":
		return x.Id != uint32(0)
	case "iplace.board.v1.Board.name":
		return x.Name != ""
	case "iplace.board.v1.Board.size_x":
		return x.SizeX != uint32(0)
	case "iplace.board.v1.Board.size_y":
		return x.SizeY != uint32(0)
	case "iplace.board.v1.Board.creator":
		return x.Creator != ""
	case "iplace.board.v1.Board.admin":
		return x.Admin != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.Board"))
		}
		panic(fmt.Errorf("message iplace.board.v1.Board does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Board) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "iplace.board.v1.Board.id":
		x.Id = uint32(0)
	case "iplace.board.v1.Board.name":
		x.Name = ""
	case "iplace.board.v1.Board.size_x":
		x.SizeX = uint32(0)
	case "iplace.board.v1.Board.size_y":
		x.SizeY = uint32(0)
	case "iplace.board.v1.Board.creator":
		x.Creator = ""
	case "iplace.board.v1.Board.admin":
		x.Admin = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.Board"))
		}
		panic(fmt.Errorf("message iplace.board.v1.Board does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Board) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "iplace.board.v1.Board.id":
		value := x.Id
		return protoreflect.ValueOfUint32(value)
	case "iplace.board.v1.Board.name":
		value := x.Name
		return protoreflect.ValueOfString(value)
	case "iplace.board.v1.Board.size_x":
		value := x.SizeX
		return protoreflect.ValueOfUint32(value)
	case "iplace.board.v1.Board.size_y":
		value := x.SizeY
		return protoreflect.ValueOfUint32(value)
	case "iplace.board.v1.Board.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	case "iplace.board.v1.Board.admin":
		value := x.Admin
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.Board"))
		}
		panic(fmt.Errorf("message iplace.board.v1.Board does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Board) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "iplace.board.v1.Board.id":
		x.Id = uint32(value.Uint())
	case "iplace.board.v1.Board.name":
		x.Name = value.Interface().(string)
	case "iplace.board.v1.Board.size_x":
		x.SizeX = uint32(value.Uint())
	case "iplace.board.v1.Board.size_y":
		x.SizeY = uint32(value.Uint())
	case "iplace.board.v1.Board.creator":
		x.Creator = value.Interface().(string)
	case "iplace.board.v1.Board.admin":
		x.Admin = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.Board"))
		}
		panic(fmt.Errorf("message iplace.board.v1.Board does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Board) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "iplace.board.v1.Board.id":
		panic(fmt.Errorf("field id of message iplace.board.v1.Board is not mutable"))
	case "iplace.board.v1.Board.name":
		panic(fmt.Errorf("field name of message iplace.board.v1.Board is not mutable"))
	case "iplace.board.v1.Board.size_x":
		panic(fmt.Errorf("field size_x of message iplace.board.v1.Board is not mutable"))
	case "iplace.board.v1.Board.size_y":
		panic(fmt.Errorf("field size_y of message iplace.board.v1.Board is not mutable"))
	case "iplace.board.v1.Board.creator":
		panic(fmt.Errorf("field creator of message iplace.board.v1.Board is not mutable"))
	case "iplace.board.v1.Board.admin":
		panic(fmt.Errorf("field admin of message iplace.board.v1.Board is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.Board"))
		}
		panic(fmt.Errorf("message iplace.board.v1.Board does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Board) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "iplace.board.v1.Board.id":
		return protoreflect.ValueOfUint32(uint32(0))
	case "iplace.board.v1.Board.name":
		return protoreflect.ValueOfString("")
	case "iplace.board.v1.Board.size_x":
		return protoreflect.ValueOfUint32(uint32(0))
	case "iplace.board.v1.Board.size_y":
		return protoreflect.ValueOfUint32(uint32(0))
	case "iplace.board.v1.Board.creator":
		return protoreflect.ValueOfString("")
	case "iplace.board.v1.Board.admin":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.Board"))
		}
		panic(fmt.Errorf("message iplace.board.v1.Board does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Board) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in iplace.board.v1.Board", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Board) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Board) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Board) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Board) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Board)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		l = len(x.Name)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.SizeX != 0 {
			n += 1 + runtime.Sov(uint64(x.SizeX))
		}
		if x.SizeY != 0 {
			n += 1 + runtime.Sov(uint64(x.SizeY))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Admin)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Board)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Admin) > 0 {
			i -= len(x.Admin)
			copy(dAtA[i:], x.Admin)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Admin)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x3a
		}
		if x.SizeY != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.SizeY))
			i--
			dAtA[i] = 0x20
		}
		if x.SizeX != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.SizeX))
			i--
			dAtA[i] = 0x18
		}
		if len(x.Name) > 0 {
			i -= len(x.Name)
			copy(dAtA[i:], x.Name)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Name)))
			i--
			dAtA[i] = 0x12
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Board)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Board: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Board: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Name = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SizeX", wireType)
				}
				x.SizeX = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.SizeX |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SizeY", wireType)
				}
				x.SizeY = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.SizeY |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Admin = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_PixelInfo             protoreflect.MessageDescriptor
	fd_PixelInfo_board_id    protoreflect.FieldDescriptor
	fd_PixelInfo_pixel_index protoreflect.FieldDescriptor
	fd_PixelInfo_color       protoreflect.FieldDescriptor
	fd_PixelInfo_setter      protoreflect.FieldDescriptor
)

func init() {
	file_iplace_board_v1_board_proto_init()
	md_PixelInfo = File_iplace_board_v1_board_proto.Messages().ByName("PixelInfo")
	fd_PixelInfo_board_id = md_PixelInfo.Fields().ByName("board_id")
	fd_PixelInfo_pixel_index = md_PixelInfo.Fields().ByName("pixel_index")
	fd_PixelInfo_color = md_PixelInfo.Fields().ByName("color")
	fd_PixelInfo_setter = md_PixelInfo.Fields().ByName("setter")
}

var _ protoreflect.Message = (*fastReflection_PixelInfo)(nil)

type fastReflection_PixelInfo PixelInfo

func (x *PixelInfo) ProtoReflect() protoreflect.Message {
	return (*fastReflection_PixelInfo)(x)
}

func (x *PixelInfo) slowProtoReflect() protoreflect.Message {
	mi := &file_iplace_board_v1_board_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_PixelInfo_messageType fastReflection_PixelInfo_messageType
var _ protoreflect.MessageType = fastReflection_PixelInfo_messageType{}

type fastReflection_PixelInfo_messageType struct{}

func (x fastReflection_PixelInfo_messageType) Zero() protoreflect.Message {
	return (*fastReflection_PixelInfo)(nil)
}
func (x fastReflection_PixelInfo_messageType) New() protoreflect.Message {
	return new(fastReflection_PixelInfo)
}
func (x fastReflection_PixelInfo_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_PixelInfo
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_PixelInfo) Descriptor() protoreflect.MessageDescriptor {
	return md_PixelInfo
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_PixelInfo) Type() protoreflect.MessageType {
	return _fastReflection_PixelInfo_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_PixelInfo) New() protoreflect.Message {
	return new(fastReflection_PixelInfo)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_PixelInfo) Interface() protoreflect.ProtoMessage {
	return (*PixelInfo)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_PixelInfo) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.BoardId != uint32(0) {
		value := protoreflect.ValueOfUint32(x.BoardId)
		if !f(fd_PixelInfo_board_id, value) {
			return
		}
	}
	if x.PixelIndex != uint32(0) {
		value := protoreflect.ValueOfUint32(x.PixelIndex)
		if !f(fd_PixelInfo_pixel_index, value) {
			return
		}
	}
	if x.Color != uint32(0) {
		value := protoreflect.ValueOfUint32(x.Color)
		if !f(fd_PixelInfo_color, value) {
			return
		}
	}
	if x.Setter != "" {
		value := protoreflect.ValueOfString(x.Setter)
		if !f(fd_PixelInfo_setter, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_PixelInfo) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "iplace.board.v1.PixelInfo.board_id":
		return x.BoardId != uint32(0)
	case "iplace.board.v1.PixelInfo.pixel_index":
		return x.PixelIndex != uint32(0)
	case "iplace.board.v1.PixelInfo.color":
		return x.Color != uint32(0)
	case "iplace.board.v1.PixelInfo.setter":
		return x.Setter != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.PixelInfo"))
		}
		panic(fmt.Errorf("message iplace.board.v1.PixelInfo does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PixelInfo) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "iplace.board.v1.PixelInfo.board_id":
		x.BoardId = uint32(0)
	case "iplace.board.v1.PixelInfo.pixel_index":
		x.PixelIndex = uint32(0)
	case "iplace.board.v1.PixelInfo.color":
		x.Color = uint32(0)
	case "iplace.board.v1.PixelInfo.setter":
		x.Setter = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.PixelInfo"))
		}
		panic(fmt.Errorf("message iplace.board.v1.PixelInfo does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_PixelInfo) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "iplace.board.v1.PixelInfo.board_id":
		value := x.BoardId
		return protoreflect.ValueOfUint32(value)
	case "iplace.board.v1.PixelInfo.pixel_index":
		value := x.PixelIndex
		return protoreflect.ValueOfUint32(value)
	case "iplace.board.v1.PixelInfo.color":
		value := x.Color
		return protoreflect.ValueOfUint32(value)
	case "iplace.board.v1.PixelInfo.setter":
		value := x.Setter
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.PixelInfo"))
		}
		panic(fmt.Errorf("message iplace.board.v1.PixelInfo does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PixelInfo) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "iplace.board.v1.PixelInfo.board_id":
		x.BoardId = uint32(value.Uint())
	case "iplace.board.v1.PixelInfo.pixel_index":
		x.PixelIndex = uint32(value.Uint())
	case "iplace.board.v1.PixelInfo.color":
		x.Color = uint32(value.Uint())
	case "iplace.board.v1.PixelInfo.setter":
		x.Setter = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.PixelInfo"))
		}
		panic(fmt.Errorf("message iplace.board.v1.PixelInfo does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PixelInfo) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "iplace.board.v1.PixelInfo.board_id":
		panic(fmt.Errorf("field board_id of message iplace.board.v1.PixelInfo is not mutable"))
	case "iplace.board.v1.PixelInfo.pixel_index":
		panic(fmt.Errorf("field pixel_index of message iplace.board.v1.PixelInfo is not mutable"))
	case "iplace.board.v1.PixelInfo.color":
		panic(fmt.Errorf("field color of message iplace.board.v1.PixelInfo is not mutable"))
	case "iplace.board.v1.PixelInfo.setter":
		panic(fmt.Errorf("field setter of message iplace.board.v1.PixelInfo is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.PixelInfo"))
		}
		panic(fmt.Errorf("message iplace.board.v1.PixelInfo does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_PixelInfo) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "iplace.board.v1.PixelInfo.board_id":
		return protoreflect.ValueOfUint32(uint32(0))
	case "iplace.board.v1.PixelInfo.pixel_index":
		return protoreflect.ValueOfUint32(uint32(0))
	case "iplace.board.v1.PixelInfo.color":
		return protoreflect.ValueOfUint32(uint32(0))
	case "iplace.board.v1.PixelInfo.setter":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: iplace.board.v1.PixelInfo"))
		}
		panic(fmt.Errorf("message iplace.board.v1.PixelInfo does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_PixelInfo) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in iplace.board.v1.PixelInfo", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_PixelInfo) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PixelInfo) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_PixelInfo) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_PixelInfo) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*PixelInfo)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.BoardId != 0 {
			n += 1 + runtime.Sov(uint64(x.BoardId))
		}
		if x.PixelIndex != 0 {
			n += 1 + runtime.Sov(uint64(x.PixelIndex))
		}
		if x.Color != 0 {
			n += 1 + runtime.Sov(uint64(x.Color))
		}
		l = len(x.Setter)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*PixelInfo)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Setter) > 0 {
			i -= len(x.Setter)
			copy(dAtA[i:], x.Setter)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Setter)))
			i--
			dAtA[i] = 0x2a
		}
		if x.Color != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Color))
			i--
			dAtA[i] = 0x20
		}
		if x.PixelIndex != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.PixelIndex))
			i--
			dAtA[i] = 0x18
		}
		if x.BoardId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.BoardId))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*PixelInfo)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PixelInfo: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PixelInfo: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BoardId", wireType)
				}
				x.BoardId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.BoardId |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PixelIndex", wireType)
				}
				x.PixelIndex = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.PixelIndex |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Color", wireType)
				}
				x.Color = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Color |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Setter", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Setter = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: iplace/board/v1/board.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Board struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SizeX uint32 `protobuf:"varint,3,opt,name=size_x,json=sizeX,proto3" json:"size_x,omitempty"`
	SizeY uint32 `protobuf:"varint,4,opt,name=size_y,json=sizeY,proto3" json:"size_y,omitempty"`
	// uint32 reference_x = 5;
	// uint32 reference_y = 6;
	Creator string `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
	Admin   string `protobuf:"bytes,8,opt,name=admin,proto3" json:"admin,omitempty"` //  uint32 last_slice_id = 9;
}

func (x *Board) Reset() {
	*x = Board{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iplace_board_v1_board_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_iplace_board_v1_board_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Board) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Board) GetSizeX() uint32 {
	if x != nil {
		return x.SizeX
	}
	return 0
}

func (x *Board) GetSizeY() uint32 {
	if x != nil {
		return x.SizeY
	}
	return 0
}

func (x *Board) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Board) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

type PixelInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoardId uint32 `protobuf:"varint,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	// uint32 slice_id = 2;
	PixelIndex uint32 `protobuf:"varint,3,opt,name=pixel_index,json=pixelIndex,proto3" json:"pixel_index,omitempty"`
	Color      uint32 `protobuf:"varint,4,opt,name=color,proto3" json:"color,omitempty"`
	Setter     string `protobuf:"bytes,5,opt,name=setter,proto3" json:"setter,omitempty"`
}

func (x *PixelInfo) Reset() {
	*x = PixelInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iplace_board_v1_board_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PixelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixelInfo) ProtoMessage() {}

// Deprecated: Use PixelInfo.ProtoReflect.Descriptor instead.
func (*PixelInfo) Descriptor() ([]byte, []int) {
	return file_iplace_board_v1_board_proto_rawDescGZIP(), []int{1}
}

func (x *PixelInfo) GetBoardId() uint32 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

func (x *PixelInfo) GetPixelIndex() uint32 {
	if x != nil {
		return x.PixelIndex
	}
	return 0
}

func (x *PixelInfo) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *PixelInfo) GetSetter() string {
	if x != nil {
		return x.Setter
	}
	return ""
}

var File_iplace_board_v1_board_proto protoreflect.FileDescriptor

var file_iplace_board_v1_board_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x69, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x76,
	0x31, 0x2f, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x19,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd, 0x01, 0x0a, 0x05, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x69, 0x7a, 0x65, 0x5f,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x58, 0x12, 0x15,
	0x0a, 0x06, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x73, 0x69, 0x7a, 0x65, 0x59, 0x12, 0x32, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x8f, 0x01, 0x0a, 0x09, 0x50, 0x69,
	0x78, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x78, 0x65, 0x6c, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x69, 0x78, 0x65, 0x6c, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x65, 0x74,
	0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x06, 0x73, 0x65, 0x74, 0x74, 0x65, 0x72, 0x42, 0xa9, 0x01, 0x0a, 0x13,
	0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x2e, 0x76, 0x31, 0x42, 0x0a, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x28, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x69, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x2f, 0x76, 0x31, 0x3b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x49, 0x42,
	0x58, 0xaa, 0x02, 0x0f, 0x49, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f, 0x49, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5c, 0x42, 0x6f, 0x61,
	0x72, 0x64, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1b, 0x49, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5c, 0x42,
	0x6f, 0x61, 0x72, 0x64, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x49, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x3a, 0x3a, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_iplace_board_v1_board_proto_rawDescOnce sync.Once
	file_iplace_board_v1_board_proto_rawDescData = file_iplace_board_v1_board_proto_rawDesc
)

func file_iplace_board_v1_board_proto_rawDescGZIP() []byte {
	file_iplace_board_v1_board_proto_rawDescOnce.Do(func() {
		file_iplace_board_v1_board_proto_rawDescData = protoimpl.X.CompressGZIP(file_iplace_board_v1_board_proto_rawDescData)
	})
	return file_iplace_board_v1_board_proto_rawDescData
}

var file_iplace_board_v1_board_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_iplace_board_v1_board_proto_goTypes = []interface{}{
	(*Board)(nil),     // 0: iplace.board.v1.Board
	(*PixelInfo)(nil), // 1: iplace.board.v1.PixelInfo
}
var file_iplace_board_v1_board_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_iplace_board_v1_board_proto_init() }
func file_iplace_board_v1_board_proto_init() {
	if File_iplace_board_v1_board_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_iplace_board_v1_board_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Board); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iplace_board_v1_board_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PixelInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iplace_board_v1_board_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iplace_board_v1_board_proto_goTypes,
		DependencyIndexes: file_iplace_board_v1_board_proto_depIdxs,
		MessageInfos:      file_iplace_board_v1_board_proto_msgTypes,
	}.Build()
	File_iplace_board_v1_board_proto = out.File
	file_iplace_board_v1_board_proto_rawDesc = nil
	file_iplace_board_v1_board_proto_goTypes = nil
	file_iplace_board_v1_board_proto_depIdxs = nil
}
