// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: iplace/board/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateBoard struct {
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SizeX   uint32 `protobuf:"varint,3,opt,name=size_x,json=sizeX,proto3" json:"size_x,omitempty"`
	SizeY   uint32 `protobuf:"varint,4,opt,name=size_y,json=sizeY,proto3" json:"size_y,omitempty"`
	Creator string `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgCreateBoard) Reset()         { *m = MsgCreateBoard{} }
func (m *MsgCreateBoard) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBoard) ProtoMessage()    {}
func (*MsgCreateBoard) Descriptor() ([]byte, []int) {
	return fileDescriptor_43c9186ad7cb925a, []int{0}
}
func (m *MsgCreateBoard) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBoard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBoard.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBoard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBoard.Merge(m, src)
}
func (m *MsgCreateBoard) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBoard) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBoard.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBoard proto.InternalMessageInfo

func (m *MsgCreateBoard) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateBoard) GetSizeX() uint32 {
	if m != nil {
		return m.SizeX
	}
	return 0
}

func (m *MsgCreateBoard) GetSizeY() uint32 {
	if m != nil {
		return m.SizeY
	}
	return 0
}

func (m *MsgCreateBoard) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgCreateBoardResponse struct {
	Board *Board `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
}

func (m *MsgCreateBoardResponse) Reset()         { *m = MsgCreateBoardResponse{} }
func (m *MsgCreateBoardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBoardResponse) ProtoMessage()    {}
func (*MsgCreateBoardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43c9186ad7cb925a, []int{1}
}
func (m *MsgCreateBoardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBoardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBoardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBoardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBoardResponse.Merge(m, src)
}
func (m *MsgCreateBoardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBoardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBoardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBoardResponse proto.InternalMessageInfo

func (m *MsgCreateBoardResponse) GetBoard() *Board {
	if m != nil {
		return m.Board
	}
	return nil
}

type MsgSetPixel struct {
	BoardId uint32 `protobuf:"varint,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	//  uint32 slice_id = 2;
	PixelIndex uint32 `protobuf:"varint,3,opt,name=pixel_index,json=pixelIndex,proto3" json:"pixel_index,omitempty"`
	Color      uint32 `protobuf:"varint,4,opt,name=color,proto3" json:"color,omitempty"`
	Setter     string `protobuf:"bytes,5,opt,name=setter,proto3" json:"setter,omitempty"`
}

func (m *MsgSetPixel) Reset()         { *m = MsgSetPixel{} }
func (m *MsgSetPixel) String() string { return proto.CompactTextString(m) }
func (*MsgSetPixel) ProtoMessage()    {}
func (*MsgSetPixel) Descriptor() ([]byte, []int) {
	return fileDescriptor_43c9186ad7cb925a, []int{2}
}
func (m *MsgSetPixel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetPixel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetPixel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetPixel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetPixel.Merge(m, src)
}
func (m *MsgSetPixel) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetPixel) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetPixel.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetPixel proto.InternalMessageInfo

func (m *MsgSetPixel) GetBoardId() uint32 {
	if m != nil {
		return m.BoardId
	}
	return 0
}

func (m *MsgSetPixel) GetPixelIndex() uint32 {
	if m != nil {
		return m.PixelIndex
	}
	return 0
}

func (m *MsgSetPixel) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *MsgSetPixel) GetSetter() string {
	if m != nil {
		return m.Setter
	}
	return ""
}

type MsgSetPixelResponse struct {
}

func (m *MsgSetPixelResponse) Reset()         { *m = MsgSetPixelResponse{} }
func (m *MsgSetPixelResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetPixelResponse) ProtoMessage()    {}
func (*MsgSetPixelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43c9186ad7cb925a, []int{3}
}
func (m *MsgSetPixelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetPixelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetPixelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetPixelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetPixelResponse.Merge(m, src)
}
func (m *MsgSetPixelResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetPixelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetPixelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetPixelResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateBoard)(nil), "iplace.board.v1.MsgCreateBoard")
	proto.RegisterType((*MsgCreateBoardResponse)(nil), "iplace.board.v1.MsgCreateBoardResponse")
	proto.RegisterType((*MsgSetPixel)(nil), "iplace.board.v1.MsgSetPixel")
	proto.RegisterType((*MsgSetPixelResponse)(nil), "iplace.board.v1.MsgSetPixelResponse")
}

func init() { proto.RegisterFile("iplace/board/v1/tx.proto", fileDescriptor_43c9186ad7cb925a) }

var fileDescriptor_43c9186ad7cb925a = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x3d, 0x6f, 0xd3, 0x40,
	0x18, 0xc7, 0x73, 0xb4, 0x4e, 0xca, 0x45, 0x05, 0x71, 0x24, 0xc5, 0x35, 0xc8, 0x8d, 0x2c, 0x04,
	0x51, 0x44, 0x6d, 0x1a, 0xb6, 0x6e, 0x04, 0x84, 0xd4, 0x21, 0x08, 0xb9, 0x03, 0x2f, 0x4b, 0xe4,
	0xd8, 0xa7, 0xe3, 0xa4, 0xd8, 0x67, 0xf9, 0x8e, 0xca, 0x65, 0x42, 0x8c, 0x4c, 0x7c, 0x12, 0x94,
	0x81, 0x7e, 0x07, 0xc6, 0x8a, 0x89, 0x11, 0x25, 0x43, 0xbe, 0x06, 0xba, 0x17, 0xa7, 0x4d, 0x41,
	0x64, 0x89, 0xfc, 0x7f, 0xf1, 0x93, 0xe7, 0x7e, 0x3e, 0x68, 0xd3, 0x7c, 0x12, 0xc5, 0x38, 0x18,
	0xb3, 0xa8, 0x48, 0x82, 0x93, 0x83, 0x40, 0x94, 0x7e, 0x5e, 0x30, 0xc1, 0xd0, 0x4d, 0x9d, 0xf8,
	0x2a, 0xf1, 0x4f, 0x0e, 0x9c, 0x5b, 0x51, 0x4a, 0x33, 0x16, 0xa8, 0x5f, 0xdd, 0x71, 0xee, 0xc4,
	0x8c, 0xa7, 0x8c, 0x07, 0x29, 0x27, 0xf2, 0xdd, 0x94, 0x13, 0x13, 0xec, 0xea, 0x60, 0xa4, 0x54,
	0xa0, 0x85, 0x89, 0x5a, 0x84, 0x11, 0xa6, 0x7d, 0xf9, 0x64, 0xdc, 0xbb, 0x57, 0xf7, 0xd0, 0x7f,
	0xab, 0x42, 0xef, 0x1b, 0x80, 0x37, 0x86, 0x9c, 0x3c, 0x2b, 0x70, 0x24, 0xf0, 0x40, 0x06, 0x08,
	0xc1, 0xcd, 0x2c, 0x4a, 0xb1, 0x7d, 0xad, 0x03, 0xba, 0xd7, 0x43, 0xf5, 0x8c, 0xda, 0xb0, 0xce,
	0xe9, 0x47, 0x3c, 0x2a, 0xed, 0x8d, 0x0e, 0xe8, 0x6e, 0x87, 0x96, 0x54, 0x6f, 0x96, 0xf6, 0xa9,
	0xbd, 0x79, 0x61, 0xbf, 0x45, 0x7d, 0xd8, 0x88, 0xe5, 0x40, 0x56, 0xd8, 0x0d, 0x39, 0x64, 0x60,
	0xff, 0xfc, 0xbe, 0xdf, 0x32, 0xab, 0x3e, 0x4d, 0x92, 0x02, 0x73, 0x7e, 0x2c, 0x0a, 0x9a, 0x91,
	0xb0, 0x2a, 0x1e, 0x3e, 0xf8, 0xbc, 0x98, 0xf6, 0x2a, 0xf5, 0x65, 0x31, 0xed, 0xb5, 0xcd, 0xda,
	0xab, 0xdb, 0x79, 0x2f, 0xe0, 0xce, 0xaa, 0x13, 0x62, 0x9e, 0xb3, 0x8c, 0x63, 0xf4, 0x08, 0x5a,
	0xea, 0x64, 0x36, 0xe8, 0x80, 0x6e, 0xb3, 0xbf, 0xe3, 0x5f, 0xa1, 0xec, 0xeb, 0xba, 0x2e, 0x79,
	0x67, 0x00, 0x36, 0x87, 0x9c, 0x1c, 0x63, 0xf1, 0x8a, 0x96, 0x78, 0x82, 0x76, 0xe1, 0x96, 0x0a,
	0x46, 0x54, 0x0f, 0xd8, 0x0e, 0x1b, 0x4a, 0x1f, 0x25, 0x68, 0x0f, 0x36, 0x73, 0xd9, 0x19, 0xd1,
	0x2c, 0xc1, 0x15, 0x01, 0xa8, 0xac, 0x23, 0xe9, 0xa0, 0x16, 0xb4, 0x62, 0x36, 0x61, 0x45, 0x45,
	0x41, 0x09, 0xf4, 0x18, 0xd6, 0x39, 0x16, 0x02, 0x17, 0xb6, 0xb5, 0x06, 0x82, 0xe9, 0x1d, 0x7a,
	0x92, 0x81, 0x11, 0x12, 0x01, 0xba, 0x40, 0x50, 0xed, 0xe9, 0xb5, 0xe1, 0xed, 0x4b, 0xb2, 0x3a,
	0x7c, 0xff, 0x0c, 0xc0, 0x8d, 0x21, 0x27, 0xe8, 0x35, 0x6c, 0x5e, 0xfe, 0x96, 0x7b, 0x7f, 0x41,
	0x58, 0x85, 0xe7, 0x3c, 0x5c, 0x53, 0x58, 0xd2, 0x7d, 0x09, 0xb7, 0x96, 0xac, 0xee, 0xfd, 0xeb,
	0xa5, 0x2a, 0x75, 0xee, 0xff, 0x2f, 0xad, 0xe6, 0x39, 0xd6, 0xa7, 0xc5, 0xb4, 0x07, 0x06, 0xcf,
	0x7f, 0xcc, 0x5c, 0x70, 0x3e, 0x73, 0xc1, 0xef, 0x99, 0x0b, 0xbe, 0xce, 0xdd, 0xda, 0xf9, 0xdc,
	0xad, 0xfd, 0x9a, 0xbb, 0xb5, 0x77, 0x3d, 0x42, 0xc5, 0xfb, 0x0f, 0x63, 0x3f, 0x66, 0x69, 0x40,
	0x33, 0x2a, 0xf6, 0x35, 0x0b, 0x83, 0xa4, 0x34, 0xd7, 0x59, 0x9c, 0xe6, 0x98, 0x8f, 0xeb, 0xea,
	0x32, 0x3f, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xae, 0x3b, 0x7b, 0x73, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateBoard(ctx context.Context, in *MsgCreateBoard, opts ...grpc.CallOption) (*MsgCreateBoardResponse, error)
	SetPixel(ctx context.Context, in *MsgSetPixel, opts ...grpc.CallOption) (*MsgSetPixelResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateBoard(ctx context.Context, in *MsgCreateBoard, opts ...grpc.CallOption) (*MsgCreateBoardResponse, error) {
	out := new(MsgCreateBoardResponse)
	err := c.cc.Invoke(ctx, "/iplace.board.v1.Msg/CreateBoard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetPixel(ctx context.Context, in *MsgSetPixel, opts ...grpc.CallOption) (*MsgSetPixelResponse, error) {
	out := new(MsgSetPixelResponse)
	err := c.cc.Invoke(ctx, "/iplace.board.v1.Msg/SetPixel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateBoard(context.Context, *MsgCreateBoard) (*MsgCreateBoardResponse, error)
	SetPixel(context.Context, *MsgSetPixel) (*MsgSetPixelResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateBoard(ctx context.Context, req *MsgCreateBoard) (*MsgCreateBoardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBoard not implemented")
}
func (*UnimplementedMsgServer) SetPixel(ctx context.Context, req *MsgSetPixel) (*MsgSetPixelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPixel not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateBoard)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iplace.board.v1.Msg/CreateBoard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateBoard(ctx, req.(*MsgCreateBoard))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetPixel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetPixel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetPixel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iplace.board.v1.Msg/SetPixel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetPixel(ctx, req.(*MsgSetPixel))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iplace.board.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBoard",
			Handler:    _Msg_CreateBoard_Handler,
		},
		{
			MethodName: "SetPixel",
			Handler:    _Msg_SetPixel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iplace/board/v1/tx.proto",
}

func (m *MsgCreateBoard) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBoard) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBoard) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x3a
	}
	if m.SizeY != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SizeY))
		i--
		dAtA[i] = 0x20
	}
	if m.SizeX != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SizeX))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateBoardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBoardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBoardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Board != nil {
		{
			size, err := m.Board.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetPixel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetPixel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetPixel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Setter) > 0 {
		i -= len(m.Setter)
		copy(dAtA[i:], m.Setter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Setter)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Color != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Color))
		i--
		dAtA[i] = 0x20
	}
	if m.PixelIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PixelIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.BoardId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BoardId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetPixelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetPixelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetPixelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateBoard) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SizeX != 0 {
		n += 1 + sovTx(uint64(m.SizeX))
	}
	if m.SizeY != 0 {
		n += 1 + sovTx(uint64(m.SizeY))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateBoardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Board != nil {
		l = m.Board.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetPixel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BoardId != 0 {
		n += 1 + sovTx(uint64(m.BoardId))
	}
	if m.PixelIndex != 0 {
		n += 1 + sovTx(uint64(m.PixelIndex))
	}
	if m.Color != 0 {
		n += 1 + sovTx(uint64(m.Color))
	}
	l = len(m.Setter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetPixelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateBoard) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBoard: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBoard: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SizeX", wireType)
			}
			m.SizeX = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SizeX |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SizeY", wireType)
			}
			m.SizeY = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SizeY |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateBoardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBoardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBoardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Board", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Board == nil {
				m.Board = &Board{}
			}
			if err := m.Board.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetPixel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetPixel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetPixel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoardId", wireType)
			}
			m.BoardId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BoardId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PixelIndex", wireType)
			}
			m.PixelIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PixelIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Color", wireType)
			}
			m.Color = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Color |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Setter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Setter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetPixelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetPixelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetPixelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
